CREATE TABLE IF NOT EXISTS STUDENTE (
  Matricola INT PRIMARY KEY,
  Nome VARCHAR(50) NOT NULL,
  Cognome VARCHAR(50) NOT NULL,
  DataNascita DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS DOCENTE (
  IdDocente INT PRIMARY KEY,
  Nome VARCHAR(50) NOT NULL,
  Cognome VARCHAR(50) NOT NULL,
  Dipartimento VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS MATERIA (
  IdMateria INT PRIMARY KEY,
  Nome VARCHAR(100) NOT NULL,
  CFU INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ESAME (
  Matricola INT NOT NULL,
  IdMateria INT NOT NULL,
  DataEsame DATE NOT NULL,
  Voto INT NOT NULL,
  Lode TINYINT(1) NOT NULL DEFAULT 0,
  IdDocente INT NOT NULL,
  PRIMARY KEY (Matricola, IdMateria, DataEsame),
  CONSTRAINT fk_esame_studente FOREIGN KEY (Matricola)
    REFERENCES STUDENTE(Matricola)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_esame_materia FOREIGN KEY (IdMateria)
    REFERENCES MATERIA(IdMateria)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_esame_docente FOREIGN KEY (IdDocente)
    REFERENCES DOCENTE(IdDocente)
    ON DELETE RESTRICT ON UPDATE CASCADE
);
